id: IAE4B264C
ocr_import_info:
  timestamp: '2023-10-06T15:22:15.156078+00:00'
  batch_id: batch-68a2
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 16:29:21.662417+00:00
last_modified: 2023-10-06 16:29:21.662423+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG1789
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG1789
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བློ་སྦྱོང་དང་ཞལ་གདམས་ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9940289337930731
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG1834:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1834
      total_pages: 368
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1834.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9940289337930731
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
